### ISSUE TITLE
glitch remix

### ISSUE THREAD

**Issue by HandR** [pepyta/robibot#5]
hello
thank you for run this project in glitch
but Can you link the project i need remix project 
and thank you

**Comment by HandR** [comment]
im add all Environment Variables
but show this error
'Error
I can only work in music channel.'

**Comment by EllieDiscord** [comment]
I am also getting this issue.

**Comment by pepyta** [comment]
Hey guys!

That's because you didn't set the MUSIC_CHANNEL_ID in your .env file. That must be a text channel where people can write the commands for the bot. I will create a commit regarding this issue where you won't have to use that value and if you leave it blank, then it will work in all chanels.

And also sorry for my late response.

**Comment by pepyta** [comment]
Clone my updates and it should work fine for now. Also if you need a remix button then here it is: [Remix](https://glitch.com/edit/?utm_content=project_pepyta-robibot-remake&utm_source=remix_this&utm_medium=button&utm_campaign=glitchButton#!/remix/pepyta-robibot-remake)
